export enum FreezeReasonType {
  SPARE_PART_UNAVAILABLE = 'SPARE_PART_UNAVAILABLE',
  AWAITING_AUTHORIZATION = 'AWAITING_AUTHORIZATION',
  SPECIALIST_UNAVAILABLE = 'SPECIALIST_UNAVAILABLE',
  EQUIPMENT_OR_AREA_UNAVAILABLE = 'EQUIPMENT_OR_AREA_UNAVAILABLE',
  OTHER = 'OTHER',
}
