export enum TicketStatus {
  NEW = 'NEW',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  FREEZE_REQUESTED = 'FREEZE_REQUESTED',
  FROZEN = 'FROZEN',
  PENDING_REASSIGNMENT = 'PENDING_REASSIGNMENT',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}
